name = "certy"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-25"
workers_dev = true

[vars]
PUBLIC_API_BASE_URL=https://certy.com.br/api
PUBLIC_EMAIL_VALIDATION_API_URL=https://api.likn.dev/v1/public/email-validation/validate

[observability]
[observability.logs]
enabled = true
invocation_logs = true
[observability.traces]
enabled = true

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
